### ISSUE TITLE
Got "IndexError" when running format_meto_forcing.py

### ISSUE THREAD

**Issue by qingling-bao** [KMarkert/servir-vic-training#26]
Hi all
I meet this error when running format_meto_forcing.py. Could you please help to fix it?
servir-vic@vicTraining-VirtualBox:~/Documents/Ebinur_basin_vic_training/scripts$ python format_meteo_forcing.py ../data/input/gis/Ebinur_grid.tif ../data/input/forcing/raw/ ../data/input/forcing/ 2005 2013
Traceback (most recent call last):
  File "format_meteo_forcing.py", line 172, in <module>
    main()
  File "format_meteo_forcing.py", line 164, in main
    format_meteo_forcing(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5])
  File "format_meteo_forcing.py", line 122, in format_meteo_forcing
    tmaxval = np.max(tmax[cnt1:cnt2+1,idx[0],idx[1]]-273.15)
  File "netCDF4/_netCDF4.pyx", line 3753, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:40527)
  File "netCDF4/_netCDF4.pyx", line 4470, in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:51227)
IndexError

**Comment by qingling-bao** [comment]
I can provide you with data files and script files, could you check where is wrong?
thank!!!

**Comment by qingling-bao** [comment]
One thing to add, when I use format_meto_forcing.py to run the sample data, there is no output error. It may be a problem with my own data, but it hasn’t happened so far.

**Comment by motasemmtsm** [comment]
does anyone knows how to fix this error? it happens with me as well ?
