### ISSUE TITLE
Got "Index Error: Index is out of bounds for axis 1" when running make_veg_lib.py by my own Data

### ISSUE THREAD

**Issue by mrezaka** [KMarkert/servir-vic-training#30]
Hi all
I meet this error when running make_veg_lib.py for my own data,  but when i run it for Nyando_basin Data (LAI & ALB & Basin_LC_IGBP) which are already in the zip file downloaded from GitHub, i don't get the error and veg.lib output forms completely 
...........................................................................................................................................................................................
python '/home/mrk/Documents/research/servir-vic-training-master/scripts/make_veg_lib.py' '/home/mrk/Documents/research/servir-vic-training-master/data/input/gis1/landcover_LC_IGBP.tif' '/home/mrk/Documents/research/servir-vic-training-master/data/ancillary/tiff_16un-LAI/new/calcu/' '/home/mrk/Documents/research/servir-vic-training-master/data/ancillary/tif-un16-ALB/test/' '/home/mrk/Documents/research/servir-vic-training-master/data/input/example/veg.lib' IGBP
Traceback (most recent call last):
  File "/home/mrk/Documents/research/servir-vic-training-master/scripts/make_veg_lib.py", line 216, in <module>
    main()
  File "/home/mrk/Documents/research/servir-vic-training-master/scripts/make_veg_lib.py", line 210, in main
    make_veg_lib(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5])
  File "/home/mrk/Documents/research/servir-vic-training-master/scripts/make_veg_lib.py", line 149, in make_veg_lib
    lai.append(np.nanmean(laiStep[clsidx])/1000.)

IndexError: index 3576 is out of bounds for axis 1 with size 3571
...............................................................................................................................................................................................

could you please help me to know what is the problem with my "LAI & ALB" Data that this error occurs?
thanks.

**Comment by mrezaka** [comment]
it was pixel size problem due to usage of V06 of images.

**Comment by motasemmtsm** [comment]
I got the same error, does anyone knows the solution to this
